%define		mod_name	throttle
%define 	apxs		/usr/sbin/apxs1
Summary:	Bandwidth & Request Throttling for Apache
Summary(cs):	Omezení sí»ového provozu pro Apache
Summary(de):	Ein Modul, das die Bandbreiten- und Anforderungseinschränkung für Apache implementiert
Summary(es):	Módulo que implementa la gestión de ancho de banda y peticiones para Apache
Summary(fr):	Module qui met en oeuvre la bande passante et l'étranglement requis pour Apache
Summary(it):	Modulo che implementa la larghezza di banda e la richiesta di throttling per Apache
Summary(ja):	Apache ÍÑÂÓ°èÉý¤ª¤è¤ÓÍ×µá¥¹¥í¥Ã¥È¥ë¤ò¼ÂÁõ¤¹¤ë¥â¥¸¥å¡¼¥ë
Summary(pl):	T³umienie przepustowo¶ci i zapytañ dla Apache'a
Summary(pt_BR):	Descompressão "On-the-fly" de arquivos HTML para o Apache
Summary(sv):	En modul som implementerar bandvidd- och begäranbegränsningar i Apache
Name:		apache1-mod_%{mod_name}
Version:	3.1.2
Release:	1
License:	BSD-like
Group:		Networking/Daemons
Source0:	http://www.snert.com/Software/mod_throttle/mod_throttle312.tgz
# Source0-md5:	6edc45c3ea8a0855d4b0b14cf0f76404
Patch0:		apache1-mod_throttle-PLD-v6stuff.patch
URL:		http://www.snert.com/Software/mod_throttle/
BuildRequires:	%{apxs}
BuildRequires:	apache1-devel >= 1.3.1
Requires(post,preun):	%{apxs}
Requires:	apache1 >= 1.3.1
Obsoletes:	apache-mod_%{mod_name} <= %{version}
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%define		_pkglibdir	%(%{apxs} -q LIBEXECDIR)

%description
This Apache module is intended to reduce the load on your server &
bandwidth generated by popular virtual hosts, directories, locations,
or users according to supported polices (see below) that decide when
to delay or refuse requests. Also mod_throttle can track and throttle
incoming connections by IP address or by authenticated remote user.

%description -l cs
Balíèek mod_throttle obsahuje modul, který umo¾òuje omezit prùtok dat,
která odcházejí z WWW serveru Apache. Limity mohou být nastaveny pro
jednotlivé virtuální weby, adresáøe, umístìní nebo autentizované
u¾ivatele.

%description -l de
Mod_throttle kann verwendet werden, um die Datenmenge zu beschränken,
die Ihr Web-Server behandelt. Diese Einschränkungen können für
einzelne virtuelle Rechner, Verzeichnisse, Speicherstellen oder
authentifizierte Benutzer eingestellt werden.

%description -l es
Mod_throttle puede usarse para limitar la cantidad de datos que su
servidor web va a servir. Estos límites se pueden configurar para
hosts virtuales individuales, directorios, lug<res o usuarios
autenticados.

%description -l fr
Mod_throttle peut être utilisé pour limiter la quantité de données
servies par votre serveur Web. Ces limites peuvent être définies pour
des hôtes virtuels individuels, répertoires, emplacements ou
utilisateurs authentifiés.

%description -l it
Mod_throttle può essere usato per limitare la quantità di dati che il
server Web dovrà servire. Queste limitazioni possono essere
configurate per singoli host virtuali, directory, indirizzi o utenti
autenticati.

%description -l ja
Mod_throttle ¤Ë¤è¤Ã¤Æ Web ¥µ¡¼¥Ð¡¼¤¬½èÍý¤¹¤ë¥Ç¡¼¥¿ÎÌ¤òÀ©¸Â¤Ç¤­¤Þ¤¹
¤³¤ì¤é¤ÎÀ©¸Â¤Ï¡¢¸Ä¡¹¤Î²¾ÁÛ¥Û¥¹¥È¡¢¥Ç¥£¥ì¥¯¥È¥ê¡¢¾ì½ê¡¢¤Þ¤¿¤Ï
Ç§¾Ú¥æ¡¼¥¶¡¼ÍÑ¤Ë¤Ä¤¤¤ÆÀßÄê¤Ç¤­¤Þ¤¹¡£

%description -l pl
Ten modu³ Apache ma s³u¿yæ do zmniejszania obci±¿enia serwera i ruchu
generowanego przez popularne hosty wirtualne, katalogi, pliki lub
u¿ytkowników zgodnie z obs³ugiwanymi polisami, które decyduj± kiedy
opó¼niæ lub odrzuciæ zapytanie. mod_throttle mo¿e tak¿e ¶ledziæ i
t³umiæ po³±czenia przychodz±ce z danego adresu IP lub danego,
autentykuj±cego siê, u¿ytkownika.

%description -l pt_BR
Descompressão "On-the-fly" de arquivos HTML para o Apache.

%description -l sv
Mod_throttle kan användas för att begränsa mängden data som din
webbserver skickar. Dessa gränser kan sättas för enskilda virtuella
värdar, kataloger, platser eller autenticerade användare.

%prep
%setup -q -n mod_%{mod_name}-%{version}
%patch0 -p1

%build
%{apxs} -o mod_%{mod_name}.so -c mod_%{mod_name}.c

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT%{_pkglibdir}

install mod_%{mod_name}.so $RPM_BUILD_ROOT%{_pkglibdir}

sed -e 's/<!--#/<!--/g' index.shtml > mod_%{mod_name}.html

%clean
rm -rf $RPM_BUILD_ROOT

%post
%{apxs} -e -a -n throttle %{_pkglibdir}/mod_%{mod_name}.so 1>&2
if [ -f /var/lock/subsys/apache ]; then
	/etc/rc.d/init.d/apache restart 1>&2
else
	echo "Run \"/etc/rc.d/init.d/apache start\" to start apache http daemon."
fi

%preun
if [ "$1" = "0" ]; then
	%{apxs} -e -A -n throttle %{_pkglibdir}/mod_%{mod_name}.so 1>&2
	if [ -f /var/lock/subsys/apache ]; then
		/etc/rc.d/init.d/apache restart 1>&2
	fi
fi

%files
%defattr(644,root,root,755)
%doc *.txt *.html
%attr(755,root,root) %{_pkglibdir}/*
