Summary:	Bandwidth & Request Throttling
Summary(pl):	T³umienie przepustowo¶ci i zapytañ
Name:		apache-mod_throttle
Version:	3.1.2
Release:	1
License:	Anthony Howe
Group:		Networking/Daemons
Group(de):	Netzwerkwesen/Server
Group(pl):	Sieciowe/Serwery
Source0:	http://www.snert.com/Software/mod_throttle/mod_throttle312.tgz
URL:		http://www.snert.com/Software/mod_throttle/
BuildRequires:	apache-devel
Requires:	apache >= 1.3.1
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%define         _libexecdir     %{_libdir}/apache
%define         _htmldocdir     /home/httpd/manual/mod

%description
This Apache module is intended to reduce the load on your server &
bandwidth generated by popular virtual hosts, directories, locations,
or users according to supported polices (see below) that decide when
to delay or refuse requests. Also mod_throttle can track and throttle
incoming connections by IP address or by authenticated remote user.

%description -l pl
Ten modu³ Apache ma s³u¿yæ do zmniejsszania obci±¿enia serwera i ruchu
generowanego przez popularne hosty wirtualne, katalogi, pliki lub
u¿ytkowników zgodnie z obs³ugiwanymi polisami, które decyduj± kiedy
opó¼niæ lub odrzuciæ zapytanie. mod_throttle mo¿e tak¿e ¶ledziæ i
t³umiæ po³±czenia przychodz±ce z danego adresu IP lub danego,
autentykuj±cego siê, u¿ytkownika.

%prep
%setup -q -n mod_throttle-%{version}

%build
/usr/sbin/apxs -DSUEXEC_BIN="\"\\\"%{_sbindir}/suexec\\\"\"" -o mod_throttle.so -c *.c
# to don't bother about ssi counter inside
mv -f index.shtml index.html

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT{%{_libexecdir},%{_htmldocdir}}

install mod_throttle.so $RPM_BUILD_ROOT%{_libexecdir}
install *.html $RPM_BUILD_ROOT%{_htmldocdir}

gzip -9nf *.txt

%clean
rm -rf $RPM_BUILD_ROOT

%post
%{_sbindir}/apxs -e -a -n throttle %{_libexecdir}/mod_throttle.so 1>&2
if [ -f /var/lock/subsys/httpd ]; then
	/etc/rc.d/init.d/httpd restart 1>&2
else
	echo "Run \"/etc/rc.d/init.d/httpd start\" to start apache http daemon."
fi

%preun
if [ "$1" = "0" ]; then
	%{_sbindir}/apxs -e -A -n throttle %{_libexecdir}/mod_throttle.so 1>&2
	if [ -f /var/lock/subsys/httpd ]; then
		/etc/rc.d/init.d/httpd restart 1>&2
	fi
fi

%files
%defattr(644,root,root,755)
%doc *.gz
%doc %{_htmldocdir}/index.html
%attr(755,root,root) %{_libexecdir}/*
